// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-marginal-gains",
      "script": "bash",
      "args": [
        "-c",
        "bun run src/server.ts"
      ],
      "cwd": "/Users/mini/code/marginalgains",
      "env": {
        "APP_ID": "2970874b-56c5-41b5-ba59-b3bd545d3ad9",
        "APP_LABEL": "Marginal Gains",
        "USER_ALIAS": "honest-ivory-thicket"
      },
      "out_file": "/Users/mini/code/marginalgains/apps/logs/honest-ivory-thicket-app-marginal-gains-out.log",
      "error_file": "/Users/mini/code/marginalgains/apps/logs/honest-ivory-thicket-app-marginal-gains-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
